name: Build OS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, type-cpx51, in-hel1, image-x86-app-docker-ce, setup-android-build]
    env:
      cache-key: ccache
    steps:
    - uses: actions/checkout@v4

    - name: Checkout signing keys # For now a repo as there a dozens of files that are kind of hard to store as a GitHub secret
      uses: actions/checkout@v4
      with:
        repository: aos-litetex/build-signing-keys
        token: ${{ secrets.SIGNING_KEY_CHECKOUT_GH_TOKEN }}
        path: user/keys
    
    - name: Restore Cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: ./user/ccache
        key: ${{ env.cache-key }}
  
    - name: Build OS using Docker
      run: docker compose -f ci.docker-compose.yml up

    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: user/logs

    - name: Install GH CLI
      run: |
        (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
                && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
                && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
    
    - name: Delete Previous Cache
      if: ${{ steps.cache-restore.outputs.cache-hit }}
      continue-on-error: true
      run: |
        gh cache delete "${{ env.cache-key }}" --confirm
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Save Cache
      uses: actions/cache/save@v3
      with:
        path: ./user/ccache
        key: ${{ env.cache-key }}

    - run: ls -lha user/zips

    - name: Archive system image
      uses: actions/upload-artifact@v4
      with:
        name: zips
        path: user/zips/system.img
    
    - name: Checkout image creator
      uses: actions/checkout@v4
      with:
        repository: aos-litetex/huawei-creator
        path: huawei-creator
    
    - name: Build huawei-creator
      run: docker build -t huawei-creator huawei-creator

    - name: Run huawei-creator
      run: |
        docker run --rm -v $(pwd)/user/zips:/data/huawei-creator --privileged huawei-creator /data/huawei-creator/run-huawei-emui9-ab-a13.sh system.img "HydraX(LeaOS) 20" "ANE-LX1"

    - name: Rename image and compress
      working-directory: user/zips
      run: |
        mv s-vndklite.img system-ANE-LX1.img
        sudo apt-get update && sudo apt-get install -y zstd
        zstd -T0 system-ANE-LX1.img -o system-ANE-LX1.img.zst

    - name: Get version
      id: version
      run: |
        version=$(date -u '+%Y.%m.%d')
        echo "release=$version" >> $GITHUB_OUTPUT
        echo "releasenumber=${version//[!0-9]/}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create-release
      uses: shogo82148/actions-create-release@v1
      with:
        tag_name: v${{ steps.version.outputs.release }}
        release_name: v${{ steps.version.outputs.release }}
        commitish: dev
        body: |
          ## [Changelog](https://github.com/${{ github.repository }}/blob/dev/CHANGELOG.md#${{ steps.version.outputs.releasenumber }})
          See [Changelog#v${{ steps.version.outputs.release }}](https://github.com/${{ github.repository }}/blob/dev/CHANGELOG.md#${{ steps.version.outputs.releasenumber }}) for more information.
    
    - name: Upload Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: user/zips/system-ANE-LX1.img.zst
