name: Build OS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, type-cpx51, in-hel1, image-x86-app-docker-ce, setup-android-build]
    steps:
    - uses: actions/checkout@v4

    - name: Checkout signing keys # For now a repo as there a dozens of files that are kind of hard to store as a GitHub secret
      uses: actions/checkout@v4
      with:
        repository: aos-litetex/build-signing-keys
        token: ${{ secrets.SIGNING_KEY_CHECKOUT_GH_TOKEN }}
        path: user/keys

    # TODO: Cache is not updated
    - name: Cache CCache
      uses: actions/cache@v4
      with:
        path: user/ccache
        key: ccache
    
    - name: Build OS using Docker
      run: docker compose -f ci.docker-compose.yml up

    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: user/logs

    - run: ls -lha user/zips

    - name: Archive system image
      uses: actions/upload-artifact@v4
      with:
        name: zips
        path: user/zips/system.img
    
    - name: Checkout image creator
      uses: actions/checkout@v4
      with:
        repository: aos-litetex/huawei-creator
        path: huawei-creator
    
    - name: Build huawei-creator
      run: docker build -t huawei-creator huawei-creator

    - name: Run huawei-creator
      run: >-
        docker run --rm 
          -it 
          -v $(pwd)/user/zips:/data/huawei-creator 
          --privileged 
          huawei-creator 
          /data/huawei-creator/run-huawei-emui9-ab-a13.sh system.img "HydraX(LeaOS) 20" "ANE-LX1"

    - name: Rename image and compress
      working-directory: user/zips
      run: |
        mv s-vndklite.img system-ANE-LX1.img
        sudo apt-get update && sudo apt-get install -y zstd
        zstd -T0 system-ANE-LX1.img -o system-ANE-LX1.img.zst

    - name: Get version
      id: version
      run: |
        version=$(date -u '+%Y.%m.%d')
        echo "release=$version" >> $GITHUB_OUTPUT
        echo "releasenumber=${version//[!0-9]/}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create-release
      uses: shogo82148/actions-create-release@v1
      with:
        tag_name: v${{ steps.version.outputs.release }}
        release_name: v${{ steps.version.outputs.release }}
        commitish: dev
        body: |
          ## [Changelog](https://github.com/${{ github.repository }}/blob/dev/CHANGELOG.md#${{ steps.version.outputs.releasenumber }})
          See [Changelog#v${{ steps.version.outputs.release }}](https://github.com/${{ github.repository }}/blob/dev/CHANGELOG.md#${{ steps.version.outputs.releasenumber }}) for more information.
    
    - name: Upload Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: user/zips/system-ANE-LX1.img.zst
